name: build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Windows
  w32-meson:
    runs-on: windows-2022
    steps:
    - name: Win configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.5
      with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"
    - name: Checkout
      uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install meson ninja r2pipe wget --break-system-packages
    - name: Extract r2 version
      shell: bash
      run: echo "branch=`./configure -qV`" >> $GITHUB_OUTPUT
      id: r2v
    - name: Build with meson + ninja
      shell: pwsh
      run: |
        .github\vsdevenv.ps1
        meson --buildtype=release --prefix=$PWD\radare2-${{ steps.r2v.outputs.branch }}-w32 -Dc_std=c11 build
        ninja -C build -j4 install
    - name: Create zip artifact
      run: 7z a radare2-${{ steps.r2v.outputs.branch }}-w32.zip $PWD\radare2-${{ steps.r2v.outputs.branch }}-w32
#    - uses: actions/checkout@v6
#      with:
#        repository: radareorg/radare2-win-installer
#        path: ./radare2-win-installer
#    - name: Create installer
#      shell: pwsh
#      run: iscc radare2-win-installer\radare2.iss /DRadare2Location=..\radare2-install\* /DLicenseLocation=..\COPYING.LESSER /DIcoLocation=radare2.ico /DMyAppVersion=${{ steps.r2v.outputs.branch }}
    - uses: actions/upload-artifact@v7
      with:
        name: w32-meson
        path: |
          radare2-${{ steps.r2v.outputs.branch }}-w32.zip
#          radare2-win-installer\Output\radare2.exe

  w64-meson:
    runs-on: windows-2022
    steps:
    - name: Win configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.5
      with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"
    - name: Checkout
      uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Preparing nmake
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Install dependencies
      run: |
        pip install meson ninja r2pipe wget --break-system-packages
    - name: Extract r2 version
      shell: bash
      run: echo "branch=`./configure -qV`" >> $GITHUB_OUTPUT
      id: r2v
    - name: Build with meson + ninja
      shell: pwsh
      run: |
        # cmd '/c call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" "x86_64"'
        bash sys/source_bat.bash 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat' "x86_64"
        # meson_options: --default-library=shared|static -Dstatic_runtime=true --backend vs2019
        meson --buildtype=release --prefix=$PWD\radare2-${{ steps.r2v.outputs.branch }}-w64 -Dc_std=c11 build
        ninja -C build -j 1
        ninja -C build install
    - name: Create zip artifact
      run: 7z a radare2-${{ steps.r2v.outputs.branch }}-w64.zip $PWD\radare2-${{ steps.r2v.outputs.branch }}-w64
#    - uses: actions/checkout@v6
#      with:
#        repository: radareorg/radare2-win-installer
#        path: ./radare2-win-installer
#    - name: Create installer
#      shell: pwsh
#      run: iscc radare2-win-installer\radare2.iss /DRadare2Location=..\radare2-install\* /DLicenseLocation=..\COPYING.LESSER /DIcoLocation=radare2.ico /DMyAppVersion=${{ steps.r2v.outputs.branch }}
    - uses: actions/upload-artifact@v7
      with:
        name: w64-meson
        path: |
          radare2-${{ steps.r2v.outputs.branch }}-w64.zip
#          radare2-win-installer\Output\radare2.exe
  msys2-w64-meson:
    strategy:
      fail-fast: false
      matrix:
        sys: [MINGW64, UCRT64]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: base-devel git
        pacboy: >-
          cc:p
          meson:p
          ninja:p
    - name: Configure Build
      shell: msys2 {0}
      run: |
        prefix=$(case "${{ matrix.sys }}" in
          MINGW64) echo /mingw64 ;;
          UCRT64) echo /ucrt64 ;;
        esac)
        meson setup build --prefix=$prefix
    - name: Compile Project
      shell: msys2 {0}
      run: meson compile -C build

  # Release creation
  check_release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    outputs:
      is_release: ${{ steps.release.outputs.is }}
      tag_name: ${{ steps.release.outputs.tag }}
    needs:
      - w32-meson
      - w64-meson
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Download all git history and tags
      - name: Check if is a release
        run: |
          TAG="`git describe --exact-match --tags ${{ github.sha }} || true`"
          if [ -n "$TAG" ]; then
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "is=yes" >> $GITHUB_OUTPUT
          else
            echo "is=no" >> $GITHUB_OUTPUT
          fi
        id: release

  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && needs.check_release.outputs.is_release == 'yes' }}
    needs:
      - check_release
    runs-on: ubuntu-24.04
    env:
      ASSET_FILES: |
        dist/artifacts/w64-meson/*.zip
        dist/artifacts/w32-meson/*.zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Download all git history and tags
      - name: Extract r2 version
        shell: bash
        run: echo "branch=`./configure -qV`" >> $GITHUB_OUTPUT
        id: r2v
      - name: Prepare release notes
        run: ./sys/release-notes.sh | tee ./RELEASE_NOTES.md
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist/artifacts
      - name: Generate checksums
        run: sha256sum $ASSET_FILES | awk '{sub(".*/", "", $2); print $1"  "$2}' > checksums.txt
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          name: ${{ steps.r2v.outputs.branch }}
          tag_name: ${{ needs.check_release.outputs.tag_name }}
          body_path: ./RELEASE_NOTES.md
          draft: false
          prerelease: false
          generate_release_notes: false
          files: |
            ${{ env.ASSET_FILES }}
            checksums.txt
